name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Docker registry login
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Publish
        uses: hef/internal-tools@5bf01ab4e598dc9798700044be44edc72cf57539 # v1.17.0
        with:
          command: "docker-builder"
          image-prefix: heff
          last-only: true
          tag-suffix: slim
          dry-run: ${{github.ref != 'refs/heads/main'}}
          platforms: "linux/arm64, linux/amd64"
