name: cron

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@bd5a63ef08a70fb4484fb7c840e0a2338060f0fb # renovate: tag=v1.7.9
        with:
          command: "docker-builder"
          tag-suffix: slim
          prune: true
