name: cron

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@5a22399f3a07c6e31cc23d8a470b0daa6507382e # renovate: tag=v1.8.7
        with:
          command: "docker-builder"
          tag-suffix: slim
          prune: true
